version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.17.5
    restart: always
    ports:
      - 80:80
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    volumes_from:
      - php
    networks:
      - default_network

  php:
    container_name: php
    build: ./docker_images/php
    working_dir: /var/www/html
    expose:
      - 9000:9000
    volumes:
      - ./src:/var/www/html
      - ./configs/php/php.ini:/usr/local/etc/php/php.ini
      - composer_cache_volume:/root/.composer/cache
    networks:
      - default_network

  db:
    container_name: db
    image: mariadb:10.3.11
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_data_volume:/var/lib/mysql
      - ./configs/mariadb:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: db
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    networks:
      - default_network
  es:
    container_name: es
    image: elasticsearch:7.12.1
    restart: always
    ulimits:
        memlock:
            soft: -1
            hard: -1
    environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
        - 9200:9200
    volumes:
        - es_data_volume:/usr/share/elasticsearch/data
    networks:
      - default_network

volumes:
  db_data_volume:
  composer_cache_volume:
  es_data_volume:

networks:
  default_network:
    driver: bridge
